const WINPLAY3_SKIN='https://commons.wikimedia.org/wiki/Special:Redirect/file/WinPlay3_screenshot.gif';
export function openPreview(item,{state,saveBlob,esc,createAudioContext}){
  const old=document.getElementById('preview-window'); if(old) old.remove();
  const result=item.result||{}, rate=result.sampleRate||44100, bits=result.bitDepth||16, channels=result.channels||2;
  const quality=({cd:'CD',sp8:'SP-1200',sp16:'MPC 2000XL',sk:'SK-1'})[item.fidelity]||'CD', ch=channels===1?'MONO':'STEREO', mode=item.playmode==='loop'?'LOOP':'ONE', kbps=Math.round(rate*bits*channels/1000);
  const w=document.createElement('div'); w.id='preview-window'; w.className='preview-window';
  w.innerHTML='<div class="preview-surface"><img class="preview-skin" src="'+WINPLAY3_SKIN+'" alt="" draggable="false"><div class="wp-title-drag"></div><button class="wp-hit wp-min"></button><button class="wp-hit wp-max"></button><button class="wp-hit wp-close"></button><button class="wp-hit wp-file"></button><button class="wp-hit wp-options"></button><button class="wp-hit wp-help"></button><div class="wp-dynamic wp-track">1</div><div class="wp-dynamic wp-minutes">00</div><div class="wp-dynamic wp-seconds">00</div><div class="wp-dynamic wp-mode"><span id="wp-rate"></span><span id="wp-quality"></span></div><button class="wp-hit wp-download"></button><button class="wp-hit wp-play"></button><button class="wp-hit wp-stop"></button><button class="wp-hit wp-pause"></button><button class="wp-hit wp-back5"></button><button class="wp-hit wp-forward5"></button><div class="wp-hit wp-seek" tabindex="0"></div><div class="wp-popup wp-file-popup" hidden><button data-action="download">Save WAV</button><button data-action="close">Close</button></div><div class="wp-popup wp-options-popup" hidden><div>Playback <button data-rate="1">1×</button> <button data-rate="0.5">0.5×</button></div><div>Volume <input type="range" min="0" max="1" step="0.01" value="1"></div></div><div class="wp-popup wp-help-popup" hidden><div>Space — Play / Pause</div><div>← / → — 5 seconds</div><div>Home / End — Start / End</div><div>Esc — Close</div></div></div>';
  document.body.appendChild(w);
  const q=s=>w.querySelector(s); q('#wp-rate').textContent=(rate/1000).toFixed(rate%1000?'3':'1')+' kHz  '+kbps+' kbit/s'; q('#wp-quality').textContent=quality+' '+ch+' '+mode;
  const ctx=state.ctx||(state.ctx=createAudioContext()); let buffer=result.buffer||null,source=null,gain=null,ratePlay=.5,offset=0,startedAt=0,playing=false,raf=0;
  const minEl=q('.wp-minutes'),secEl=q('.wp-seconds'),seek=q('.wp-seek'),vol=q('.wp-options-popup input'),filename=()=>item.file.name.replace(/\.[^.]+$/,'')+'_x2.wav';
  const pos=()=>!buffer?0:playing?Math.min(buffer.duration,offset+(ctx.currentTime-startedAt)*ratePlay):Math.min(buffer.duration,offset);
  const sync=()=>{const p=pos();minEl.textContent=String(Math.floor(p/60)).padStart(2,'0');secEl.textContent=String(Math.floor(p%60)).padStart(2,'0');seek.setAttribute('aria-valuenow',String(buffer&&buffer.duration?Math.round(p/buffer.duration*100):0));if(playing)raf=requestAnimationFrame(sync)};
  const stopSource=()=>{if(source){source.onended=null;try{source.stop()}catch(e){}source.disconnect();source=null}if(gain){gain.disconnect();gain=null}playing=false;cancelAnimationFrame(raf)};
  const start=()=>{if(!buffer)return;if(offset>=buffer.duration)offset=0;ctx.resume?.();source=ctx.createBufferSource();source.buffer=buffer;source.playbackRate.value=ratePlay;gain=ctx.createGain();gain.gain.value=+vol.value;source.connect(gain).connect(ctx.destination);startedAt=ctx.currentTime;playing=true;source.onended=()=>{if(!playing)return;if(item.playmode==='loop'){offset=0;stopSource();start();return}offset=buffer.duration;stopSource();sync()};source.start(0,offset);sync()};
  const seekTo=p=>{if(!buffer)return;const was=playing;stopSource();offset=Math.max(0,Math.min(buffer.duration,p));sync();if(was)start()};
  const close=()=>{stopSource();w.remove();window.removeEventListener('keydown',onKey)};
  const onKey=e=>{if(!document.body.contains(w))return;if(e.key==='Escape'){close();return}if(e.target.matches('input,button'))return;if(e.code==='Space'){e.preventDefault();playing?seekTo(pos()):start()}else if(e.key==='ArrowLeft')seekTo(pos()-5);else if(e.key==='ArrowRight')seekTo(pos()+5);else if(e.key==='Home')seekTo(0);else if(e.key==='End')seekTo(buffer?buffer.duration:0)};
  q('.wp-play').onclick=start; q('.wp-pause').onclick=()=>{if(playing)seekTo(pos())}; q('.wp-stop').onclick=()=>{stopSource();offset=0;sync()}; q('.wp-back5').onclick=()=>seekTo(pos()-5); q('.wp-forward5').onclick=()=>seekTo(pos()+5);
  seek.onclick=e=>{if(!buffer)return;const r=seek.getBoundingClientRect();seekTo((e.clientX-r.left)/r.width*buffer.duration)}; seek.onkeydown=e=>{if(e.key==='ArrowLeft')seekTo(pos()-5);if(e.key==='ArrowRight')seekTo(pos()+5);if(e.key==='Home')seekTo(0);if(e.key==='End')seekTo(buffer?buffer.duration:0)};
  const popups=[q('.wp-file-popup'),q('.wp-options-popup'),q('.wp-help-popup')],closePopups=()=>popups.forEach(p=>p.hidden=true);
  q('.wp-file').onclick=()=>{const p=popups[0],open=p.hidden;closePopups();p.hidden=!open}; q('.wp-options').onclick=()=>{const p=popups[1],open=p.hidden;closePopups();p.hidden=!open}; q('.wp-help').onclick=()=>{const p=popups[2],open=p.hidden;closePopups();p.hidden=!open};
  q('[data-action="download"]').onclick=()=>saveBlob(result.blob,filename()); q('[data-action="close"]').onclick=close; q('.wp-download').onclick=()=>saveBlob(result.blob,filename()); q('.wp-close').onclick=close; q('.wp-min').onclick=()=>w.classList.toggle('preview-minimized'); q('.wp-max').onclick=()=>w.classList.toggle('preview-maximized');
  q('.wp-options-popup').querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{const p=pos(),was=playing;stopSource();offset=p;ratePlay=+b.dataset.rate;if(was)start()}); vol.oninput=()=>{if(gain)gain.gain.value=+vol.value};
  let drag=false,dx=0,dy=0; const title=q('.wp-title-drag'); title.onpointerdown=e=>{if(w.classList.contains('preview-maximized'))return;drag=true;const r=w.getBoundingClientRect();dx=e.clientX-r.left;dy=e.clientY-r.top;title.setPointerCapture?.(e.pointerId)}; title.onpointermove=e=>{if(!drag)return;w.style.left=Math.max(0,Math.min(innerWidth-w.offsetWidth,e.clientX-dx))+'px';w.style.top=Math.max(0,Math.min(innerHeight-w.offsetHeight,e.clientY-dy))+'px';w.style.transform='none'}; title.onpointerup=()=>drag=false; title.onpointercancel=()=>drag=false;
  window.addEventListener('keydown',onKey); sync();
}
