export const PRESETS=Object.freeze({
  cd:{sampleRate:44100,bitDepth:16,wavBitDepth:16,resample:'linear'},
  sp8:{sampleRate:26040,bitDepth:12,wavBitDepth:16,resample:'hold'},
  sp16:{sampleRate:46875,bitDepth:16,wavBitDepth:16,resample:'linear'},
  sk:{sampleRate:9387,bitDepth:8,wavBitDepth:8,resample:'hold'}
});
export const getPreset=(name='cd')=>PRESETS[name]||PRESETS.cd;
export function createAudioContext(){const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error('Web Audio API is not supported in this browser.');return new C();}
export async function decodeAudio(arrayBuffer,ctx){try{return await ctx.decodeAudioData(arrayBuffer.slice(0));}catch(e){throw Error(`Audio decoding failed: ${e?.message||e}`);}}
function makeBuffer(length,sampleRate,channels){if(typeof AudioBuffer==='undefined')throw Error('AudioBuffer is unavailable.');return new AudioBuffer({length:Math.max(1,Math.floor(length)),sampleRate,numberOfChannels:channels});}
function checkCancel(hooks){if(hooks?.shouldCancel?.())throw Object.assign(new Error('Processing cancelled'),{name:'AbortError'});}
const yieldControl=()=>new Promise(resolve=>setTimeout(resolve,0));
export async function trimSilence(buffer,thresholdDb=-60,minSilenceDuration=.1,hooks={}){if(!buffer?.length)return buffer;const threshold=10**(thresholdDb/20),sr=buffer.sampleRate,ch=buffer.numberOfChannels,d=Array.from({length:ch},(_,i)=>buffer.getChannelData(i));let start=0,end=buffer.length;while(start<end){checkCancel(hooks);let loud=false;for(let c=0;c<ch&&!loud;c++)loud=Math.abs(d[c][start])>threshold;if(loud)break;start++;if(start%10000===0)await yieldControl();}while(end>start){checkCancel(hooks);let loud=false;for(let c=0;c<ch&&!loud;c++)loud=Math.abs(d[c][end-1])>threshold;if(loud)break;end--;if(end%10000===0)await yieldControl();}const min=Math.floor(minSilenceDuration*sr);if(start<min)start=0;if(buffer.length-end<min)end=buffer.length;if(!start&&end===buffer.length)return buffer;if(end<=start)return buffer;const out=makeBuffer(end-start,sr,ch);for(let c=0;c<ch;c++){const src=d[c],dst=out.getChannelData(c);for(let i=0;i<src.length&&i<dst.length;i++){if(i%50000===0){checkCancel(hooks);await yieldControl();}dst[i]=src[i+start];}}return out;}
export async function convertChannels(buffer,target,hooks={}){if(buffer.numberOfChannels===target)return buffer;const out=makeBuffer(buffer.length,buffer.sampleRate,target),src=Array.from({length:buffer.numberOfChannels},(_,c)=>buffer.getChannelData(c));if(target===1){const d=out.getChannelData(0),scale=1/src.length;for(let i=0;i<buffer.length;i++){if(i%50000===0){checkCancel(hooks);await yieldControl();}let x=0;for(const s of src)x+=s[i];d[i]=x*scale;}}else{const l=out.getChannelData(0),r=out.getChannelData(1);if(src.length===1){for(let i=0;i<buffer.length;i++){if(i%50000===0){checkCancel(hooks);await yieldControl();}l[i]=src[0][i];r[i]=src[0][i];}}else{for(let i=0;i<buffer.length;i++){if(i%50000===0){checkCancel(hooks);await yieldControl();}l[i]=src[0][i];r[i]=src[1][i];}}}return out;}
export async function speedAndResample(buffer,speed=2,targetSampleRate=44100,hooks={},mode='linear'){if(!(speed>0))throw Error('Speed must be greater than zero.');const outLength=Math.max(1,Math.round(buffer.length*targetSampleRate/(buffer.sampleRate*speed))),out=makeBuffer(outLength,targetSampleRate,buffer.numberOfChannels),srcRate=buffer.sampleRate;for(let c=0;c<buffer.numberOfChannels;c++){const s=buffer.getChannelData(c),d=out.getChannelData(c);for(let i=0;i<outLength;i++){if(i%20000===0){checkCancel(hooks);await yieldControl();}const pos=i*srcRate*speed/targetSampleRate;if(mode==='hold'){d[i]=s[Math.min(s.length-1,Math.max(0,Math.round(pos)))]||0;}else{const a=Math.floor(pos),f=pos-a;d[i]=a>=s.length-1?s[s.length-1]||0:s[a]*(1-f)+s[a+1]*f;}}}return out;}
export async function quantizeBuffer(buffer,bits,hooks={}){if(bits!==8&&bits!==12&&bits!==16)throw Error(`Unsupported bit depth: ${bits}`);if(bits===16)return buffer;const out=makeBuffer(buffer.length,buffer.sampleRate,buffer.numberOfChannels),levels=bits===8?127:2047;for(let c=0;c<buffer.numberOfChannels;c++){const s=buffer.getChannelData(c),d=out.getChannelData(c);for(let i=0;i<s.length;i++){if(i%20000===0){checkCancel(hooks);await yieldControl();}const x=Math.max(-1,Math.min(1,s[i]));d[i]=x<0?Math.round(x*(levels+1))/(levels+1):Math.round(x*levels)/levels;}}return out;}
function writeAscii(view,offset,text){for(let i=0;i<text.length;i++)view.setUint8(offset+i,text.charCodeAt(i));}
function makeKo2ListChunk(playmode='oneshot'){const mode=playmode==='loop'?'loop':'oneshot';const json=JSON.stringify({"sound.amplitude":100,"sound.pan":0,"sound.pitch":0,"envelope.attack":0,"envelope.release":255,"sound.playmode":mode,"sound.rootnote":60,"time.mode":"off"});const listPayloadSize=176;const out=new Uint8Array(8+listPayloadSize);const v=new DataView(out.buffer);writeAscii(v,0,'LIST');v.setUint32(4,listPayloadSize,true);writeAscii(v,8,'INFO');writeAscii(v,12,'TNGE');v.setUint32(16,json.length,true);for(let i=0;i<json.length;i++)v.setUint8(20+i,json.charCodeAt(i));v.setUint8(20+json.length,0);return out;}
function makeSmplChunk(){const out=new Uint8Array(44);const v=new DataView(out.buffer);writeAscii(v,0,'smpl');v.setUint32(4,36,true);return out;}
export async function encodeWav(buffer,bits=16,hooks={},playmode='oneshot'){if(bits!==8&&bits!==16)throw Error(`WAV PCM output supports 8-bit or 16-bit containers only; got ${bits}-bit.`);const ch=Math.min(2,buffer.numberOfChannels),bps=bits/8,frames=buffer.length,size=frames*ch*bps,smpl=makeSmplChunk(),list=makeKo2ListChunk(playmode),riffSize=4+(8+16)+smpl.length+list.length+(8+size),out=new ArrayBuffer(8+riffSize),v=new DataView(out),w=(o,s)=>writeAscii(v,o,s);w(0,'RIFF');v.setUint32(4,riffSize,true);w(8,'WAVE');let header=12;w(header,'fmt ');v.setUint32(header+4,16,true);v.setUint16(header+8,1,true);v.setUint16(header+10,ch,true);v.setUint32(header+12,buffer.sampleRate,true);v.setUint32(header+16,buffer.sampleRate*ch*bps,true);v.setUint16(header+20,ch*bps,true);v.setUint16(header+22,bits,true);header+=24;new Uint8Array(out,header,smpl.length).set(smpl);header+=smpl.length;new Uint8Array(out,header,list.length).set(list);header+=list.length;w(header,'data');v.setUint32(header+4,size,true);const data=Array.from({length:ch},(_,c)=>buffer.getChannelData(c));let o=header+8;for(let i=0;i<frames;i++){if(i%20000===0){checkCancel(hooks);await yieldControl();}for(let c=0;c<ch;c++){const x=Math.max(-1,Math.min(1,data[c][i]));if(bits===8)v.setUint8(o++,Math.max(0,Math.min(255,Math.round((x+1)*127.5))));else{v.setInt16(o,x<0?Math.round(x*32768):Math.round(x*32767),true);o+=2;}}}return new Blob([out],{type:'audio/wav'});}
export async function processAudio(input,{speed=2,fidelity='cd',channels='stereo',playmode='oneshot',autoTrim=true,context}={},hooks={}){const p=getPreset(fidelity),ctx=context||createAudioContext();checkCancel(hooks);hooks.progress?.(.05,'Decoding');let b=await decodeAudio(input,ctx);checkCancel(hooks);if(autoTrim){hooks.progress?.(.2,'Auto-trim');b=await trimSilence(b,-60,.1,hooks);}checkCancel(hooks);hooks.progress?.(.35,'Channels');b=await convertChannels(b,channels==='mono'?1:2,hooks);checkCancel(hooks);hooks.progress?.(.55,'Speed ×2');b=await speedAndResample(b,speed,p.sampleRate,hooks,p.resample);checkCancel(hooks);hooks.progress?.(.82,'Quantization');b=await quantizeBuffer(b,p.bitDepth,hooks);checkCancel(hooks);hooks.progress?.(.92,'WAV encoding');const blob=await encodeWav(b,p.wavBitDepth,hooks,playmode);hooks.progress?.(1,'Done');return{buffer:b,blob,sampleRate:p.sampleRate,bitDepth:p.bitDepth,channels:channels==='mono'?1:2};}
