export const PRESETS=Object.freeze({cd:{sampleRate:44100,bitDepth:16},sp8:{sampleRate:22050,bitDepth:8},sp16:{sampleRate:22050,bitDepth:16},sk:{sampleRate:9000,bitDepth:8}});
export const getPreset=(name='cd')=>PRESETS[name]||PRESETS.cd;
export function createAudioContext(){const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error('Web Audio API is not supported in this browser.');return new C();}
export async function decodeAudio(arrayBuffer,ctx){try{return await ctx.decodeAudioData(arrayBuffer.slice(0));}catch(e){throw Error(`Audio decoding failed: ${e?.message||e}`);}}
function makeBuffer(length,sampleRate,channels){if(typeof AudioBuffer==='undefined')throw Error('AudioBuffer is unavailable.');return new AudioBuffer({length:Math.max(1,Math.floor(length)),sampleRate,numberOfChannels:channels});}
function checkCancel(hooks){if(hooks?.shouldCancel?.())throw Object.assign(new Error('Processing cancelled'),{name:'AbortError'});}
const yieldControl=()=>new Promise(resolve=>setTimeout(resolve,0));
export async function trimSilence(buffer,thresholdDb=-60,minSilenceDuration=.1,hooks={}){if(!buffer?.length)return buffer;const threshold=10**(thresholdDb/20),sr=buffer.sampleRate,ch=buffer.numberOfChannels,d=Array.from({length:ch},(_,i)=>buffer.getChannelData(i));let start=0,end=buffer.length;while(start<end){checkCancel(hooks);let loud=false;for(let c=0;c<ch&&!loud;c++)loud=Math.abs(d[c][start])>threshold;if(loud)break;start++;if(start%10000===0)await yieldControl();}while(end>start){checkCancel(hooks);let loud=false;for(let c=0;c<ch&&!loud;c++)loud=Math.abs(d[c][end-1])>threshold;if(loud)break;end--;if(end%10000===0)await yieldControl();}const min=Math.floor(minSilenceDuration*sr);if(start<min)start=0;if(buffer.length-end<min)end=buffer.length;if(!start&&end===buffer.length)return buffer;if(end<=start)return buffer;const out=makeBuffer(end-start,sr,ch);for(let c=0;c<ch;c++)out.getChannelData(c).set(d[c].subarray(start,end));return out;}
export async function convertChannels(buffer,target,hooks={}){if(buffer.numberOfChannels===target)return buffer;const out=makeBuffer(buffer.length,buffer.sampleRate,target),src=Array.from({length:buffer.numberOfChannels},(_,c)=>buffer.getChannelData(c));if(target===1){const d=out.getChannelData(0),scale=1/src.length;for(let i=0;i<buffer.length;i++){checkCancel(i%50000===0?hooks:null);let x=0;for(const s of src)x+=s[i];d[i]=x*scale;if(i%50000===0)await yieldControl();}}else{const l=out.getChannelData(0),r=out.getChannelData(1);if(src.length===1){for(let i=0;i<buffer.length;i++){checkCancel(i%50000===0?hooks:null);l[i]=src[0][i];r[i]=src[0][i];if(i%50000===0)await yieldControl();}}else{for(let i=0;i<buffer.length;i++){checkCancel(i%50000===0?hooks:null);l[i]=src[0][i];r[i]=src[1][i];if(i%50000===0)await yieldControl();}}}return out;}
export async function speedAndResample(buffer,speed=2,targetSampleRate=44100,hooks={}){if(!(speed>0))throw Error('Speed must be greater than zero.');const outLength=Math.max(1,Math.round(buffer.length*targetSampleRate/(buffer.sampleRate*speed))),out=makeBuffer(outLength,targetSampleRate,buffer.numberOfChannels),srcRate=buffer.sampleRate;for(let c=0;c<buffer.numberOfChannels;c++){const s=buffer.getChannelData(c),d=out.getChannelData(c);for(let i=0;i<outLength;i++){if(i%50000===0){checkCancel(hooks);await yieldControl();}const pos=i*srcRate*speed/targetSampleRate,a=Math.floor(pos),f=pos-a;d[i]=a>=s.length-1?s[s.length-1]||0:s[a]*(1-f)+s[a+1]*f;}}return out;}
export async function quantizeBuffer(buffer,bits,hooks={}){if(bits===16)return buffer;if(bits!==8)throw Error(`Unsupported bit depth: ${bits}`);const out=makeBuffer(buffer.length,buffer.sampleRate,buffer.numberOfChannels),dither=1/256;for(let c=0;c<buffer.numberOfChannels;c++){const s=buffer.getChannelData(c),d=out.getChannelData(c);for(let i=0;i<s.length;i++){if(i%50000===0){checkCancel(hooks);await yieldControl();}const x=Math.max(-1,Math.min(1,s[i]));d[i]=Math.max(-1,Math.min(1,Math.round((x+1)*127)/127-1));if(Math.abs(d[i])<dither)d[i]=0;}}return out;}
export async function encodeWav(buffer,bits=16,hooks={}){const ch=Math.min(2,buffer.numberOfChannels),bps=bits/8,frames=buffer.length,size=frames*ch*bps,out=new ArrayBuffer(44+size),v=new DataView(out),w=(o,s)=>[...s].forEach((x,i)=>v.setUint8(o+i,x.charCodeAt(0)));w(0,'RIFF');v.setUint32(4,36+size,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,buffer.sampleRate,true);v.setUint32(28,buffer.sampleRate*ch*bps,true);v.setUint16(32,ch*bps,true);v.setUint16(34,bits,true);w(36,'data');v.setUint32(40,size,true);const data=Array.from({length:ch},(_,c)=>buffer.getChannelData(c));let o=44;for(let i=0;i<frames;i++){if(i%50000===0){checkCancel(hooks);await yieldControl();}for(let c=0;c<ch;c++){const x=Math.max(-1,Math.min(1,data[c][i]));if(bits===8)v.setUint8(o++,Math.max(0,Math.min(255,Math.round((x+1)*127.5))));else{v.setInt16(o,x<0?Math.round(x*32768):Math.round(x*32767),true);o+=2;}}}return new Blob([out],{type:'audio/wav'});}
export async function processAudio(input,{speed=2,fidelity='cd',channels='stereo',autoTrim=true,context}={},hooks={}){const p=getPreset(fidelity),ctx=context||createAudioContext();checkCancel(hooks);hooks.progress?.(.05,'Decoding');let b=await decodeAudio(input,ctx);checkCancel(hooks);if(autoTrim){hooks.progress?.(.2,'Auto-trim');b=await trimSilence(b,-60,.1,hooks);}checkCancel(hooks);hooks.progress?.(.35,'Channels');b=await convertChannels(b,channels==='mono'?1:2,hooks);checkCancel(hooks);hooks.progress?.(.55,'Speed ×2');b=await speedAndResample(b,speed,p.sampleRate,hooks);checkCancel(hooks);hooks.progress?.(.82,'Quantization');b=await quantizeBuffer(b,p.bitDepth,hooks);checkCancel(hooks);hooks.progress?.(.92,'WAV encoding');const blob=await encodeWav(b,p.bitDepth,hooks);hooks.progress?.(1,'Done');return{buffer:b,blob,sampleRate:p.sampleRate,bitDepth:p.bitDepth,channels:channels==='mono'?1:2};}
