export const PRESETS=Object.freeze({cd:{sampleRate:44100,bitDepth:16},sp8:{sampleRate:22050,bitDepth:8},sp16:{sampleRate:22050,bitDepth:16},sk:{sampleRate:9000,bitDepth:8}});
export const getPreset=(name='cd')=>PRESETS[name]||PRESETS.cd;
export function createAudioContext(){const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error('Web Audio API is not supported in this browser.');return new C();}
export async function decodeAudio(arrayBuffer,ctx){try{return await ctx.decodeAudioData(arrayBuffer.slice(0));}catch(e){throw Error(`Audio decoding failed: ${e?.message||e}`);}}
function makeBuffer(length,sampleRate,channels){if(typeof AudioBuffer==='undefined')throw Error('AudioBuffer is unavailable.');return new AudioBuffer({length:Math.max(1,Math.floor(length)),sampleRate,numberOfChannels:channels});}
export function trimSilence(buffer,thresholdDb=-60,minSilenceDuration=.1){if(!buffer?.length)return buffer;const threshold=10**(thresholdDb/20),sr=buffer.sampleRate,ch=buffer.numberOfChannels,d=Array.from({length:ch},(_,i)=>buffer.getChannelData(i));let start=0,end=buffer.length;while(start<end){let loud=false;for(let c=0;c<ch&&!loud;c++)loud=Math.abs(d[c][start])>threshold;if(loud)break;start++;}while(end>start){let loud=false;for(let c=0;c<ch&&!loud;c++)loud=Math.abs(d[c][end-1])>threshold;if(loud)break;end--;}const min=Math.floor(minSilenceDuration*sr);if(start<min)start=0;if(buffer.length-end<min)end=buffer.length;if(!start&&end===buffer.length)return buffer;if(end<=start)return buffer;const out=makeBuffer(end-start,sr,ch);for(let c=0;c<ch;c++)out.getChannelData(c).set(d[c].subarray(start,end));return out;}
export function convertChannels(buffer,target){if(buffer.numberOfChannels===target)return buffer;const out=makeBuffer(buffer.length,buffer.sampleRate,target),src=Array.from({length:buffer.numberOfChannels},(_,c)=>buffer.getChannelData(c));if(target===1){const d=out.getChannelData(0);const scale=1/src.length;for(let i=0;i<buffer.length;i++){let x=0;for(const s of src)x+=s[i];d[i]=x*scale;}}else{const l=out.getChannelData(0),r=out.getChannelData(1);if(src.length===1){l.set(src[0]);r.set(src[0]);}else{l.set(src[0]);r.set(src[1]);}}return out;}
export function speedAndResample(buffer,speed=2,targetSampleRate=44100){if(!(speed>0))throw Error('Speed must be greater than zero.');const outLength=Math.max(1,Math.round(buffer.length*targetSampleRate/(buffer.sampleRate*speed))),out=makeBuffer(outLength,targetSampleRate,buffer.numberOfChannels),srcRate=buffer.sampleRate;for(let c=0;c<buffer.numberOfChannels;c++){const s=buffer.getChannelData(c),d=out.getChannelData(c);for(let i=0;i<outLength;i++){const pos=i*srcRate*speed/targetSampleRate;const a=Math.floor(pos),f=pos-a;if(a>=s.length-1)d[i]=s[s.length-1]||0;else d[i]=s[a]*(1-f)+s[a+1]*f;}}return out;}
export function quantizeBuffer(buffer,bits){if(bits===16)return buffer;if(bits!==8)throw Error(`Unsupported bit depth: ${bits}`);const out=makeBuffer(buffer.length,buffer.sampleRate,buffer.numberOfChannels),dither=1/256;for(let c=0;c<buffer.numberOfChannels;c++){const s=buffer.getChannelData(c),d=out.getChannelData(c);for(let i=0;i<s.length;i++){const x=Math.max(-1,Math.min(1,s[i]));d[i]=Math.max(-1,Math.min(1,Math.round((x+1)*127)/127-1));if(Math.abs(d[i])<dither)d[i]=0;}}return out;}
export function encodeWav(buffer,bits=16){const ch=Math.min(2,buffer.numberOfChannels),bps=bits/8,frames=buffer.length,size=frames*ch*bps,out=new ArrayBuffer(44+size),v=new DataView(out),w=(o,s)=>[...s].forEach((x,i)=>v.setUint8(o+i,x.charCodeAt(0)));w(0,'RIFF');v.setUint32(4,36+size,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,buffer.sampleRate,true);v.setUint32(28,buffer.sampleRate*ch*bps,true);v.setUint16(32,ch*bps,true);v.setUint16(34,bits,true);w(36,'data');v.setUint32(40,size,true);const data=Array.from({length:ch},(_,c)=>buffer.getChannelData(c));let o=44;for(let i=0;i<frames;i++)for(let c=0;c<ch;c++){const x=Math.max(-1,Math.min(1,data[c][i]));if(bits===8)v.setUint8(o++,Math.max(0,Math.min(255,Math.round((x+1)*127.5))));else{v.setInt16(o,x<0?Math.round(x*32768):Math.round(x*32767),true);o+=2;}}return new Blob([out],{type:'audio/wav'});}
export async function processAudio(input,{speed=2,fidelity='cd',channels='stereo',autoTrim=true,context}={},hooks={}){const p=getPreset(fidelity),ctx=context||createAudioContext();hooks.progress?.(.05,'Decoding');let b=await decodeAudio(input,ctx);if(autoTrim){hooks.progress?.(.2,'Auto-trim');b=trimSilence(b);}hooks.progress?.(.35,'Channels');b=convertChannels(b,channels==='mono'?1:2);hooks.progress?.(.55,'Speed ×2');b=speedAndResample(b,speed,p.sampleRate);hooks.progress?.(.82,'Quantization');b=quantizeBuffer(b,p.bitDepth);hooks.progress?.(.92,'WAV encoding');const blob=encodeWav(b,p.bitDepth);hooks.progress?.(1,'Done');return{buffer:b,blob,sampleRate:p.sampleRate,bitDepth:p.bitDepth,channels:channels==='mono'?1:2};}