export const PRESETS=Object.freeze({cd:{sampleRate:44100,bitDepth:16},sp8:{sampleRate:22050,bitDepth:8},sp16:{sampleRate:22050,bitDepth:16},sk:{sampleRate:9000,bitDepth:8}});
export const getPreset=(name='cd')=>PRESETS[name]||PRESETS.cd;
export function createAudioContext(){const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error('Web Audio API is not supported in this browser.');return new C();}
export async function decodeAudio(arrayBuffer,ctx){try{return await ctx.decodeAudioData(arrayBuffer.slice(0));}catch(e){throw Error(`Audio decoding failed: ${e?.message||e}`);}}
function makeBuffer(length,sampleRate,channels){try{return new AudioBuffer({length,sampleRate,numberOfChannels:channels});}catch{const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error('AudioBuffer is unavailable.');const c=new C(),b=c.createBuffer(channels,length,sampleRate);c.close?.();return b;}}
export function trimSilence(buffer,thresholdDb=-60,minSilenceDuration=.1){if(!buffer?.length)return buffer;const threshold=10**(thresholdDb/20),sr=buffer.sampleRate,block=1024,ch=buffer.numberOfChannels,d=Array.from({length:ch},(_,i)=>buffer.getChannelData(i));const rms=(s,e)=>{let sum=0,n=0;for(let c=0;c<ch;c++)for(let i=s;i<e;i++){sum+=d[c][i]**2;n++;}return n?Math.sqrt(sum/n):0;};let start=0,end=buffer.length,quiet=0;for(let i=0;i<buffer.length;i+=block){const e=Math.min(i+block,buffer.length);if(rms(i,e)>threshold){start=Math.max(0,i-block);break;}quiet+=e-i;}if(quiet>=buffer.length)return buffer;quiet=0;for(let i=buffer.length;i>0;i-=block){const s=Math.max(0,i-block);if(rms(s,i)>threshold){end=Math.min(buffer.length,i+block);break;}quiet+=i-s;}if(quiet>=buffer.length||end<=start)return buffer;const min=Math.floor(minSilenceDuration*sr);if(start<min)start=0;if(buffer.length-end<min)end=buffer.length;if(!start&&end===buffer.length)return buffer;const out=makeBuffer(end-start,sr,ch);for(let c=0;c<ch;c++)out.getChannelData(c).set(d[c].subarray(start,end));return out;}
export async function convertChannels(buffer,target){if(buffer.numberOfChannels===target)return buffer;const O=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!O)throw Error('OfflineAudioContext is not supported.');const ctx=new O(target,buffer.length,buffer.sampleRate),src=ctx.createBufferSource();src.buffer=buffer;if(target===1&&buffer.numberOfChannels>1){const split=ctx.createChannelSplitter(buffer.numberOfChannels),gain=ctx.createGain();gain.gain.value=1/buffer.numberOfChannels;src.connect(split);for(let c=0;c<buffer.numberOfChannels;c++)split.connect(gain,c);gain.connect(ctx.destination);}else if(target===2&&buffer.numberOfChannels===1){const merge=ctx.createChannelMerger(2);src.connect(merge,0,0);src.connect(merge,0,1);merge.connect(ctx.destination);}else src.connect(ctx.destination);src.start();return ctx.startRendering();}
export async function speedAndResample(buffer,speed=2,targetSampleRate=44100){const O=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!O)throw Error('OfflineAudioContext is not supported.');const ctx=new O(buffer.numberOfChannels,Math.max(1,Math.ceil(buffer.duration/speed*targetSampleRate)),targetSampleRate),src=ctx.createBufferSource();src.buffer=buffer;src.playbackRate.value=speed;src.connect(ctx.destination);src.start();return ctx.startRendering();}
export function quantizeBuffer(buffer,bits){if(bits===16)return buffer;if(bits!==8)throw Error(`Unsupported bit depth: ${bits}`);const out=makeBuffer(buffer.length,buffer.sampleRate,buffer.numberOfChannels),step=2/256;for(let c=0;c<buffer.numberOfChannels;c++){const s=buffer.getChannelData(c),d=out.getChannelData(c);for(let i=0;i<s.length;i++){const x=Math.max(-1,Math.min(1,s[i]));d[i]=Math.max(-1,Math.min(1,step*Math.floor(x/step+.5)));}}return out;}
export function encodeWav(buffer,bits=16){const ch=Math.min(2,buffer.numberOfChannels),bps=bits/8,frames=buffer.length,size=frames*ch*bps,out=new ArrayBuffer(44+size),v=new DataView(out),w=(o,s)=>[...s].forEach((x,i)=>v.setUint8(o+i,x.charCodeAt(0)));w(0,'RIFF');v.setUint32(4,36+size,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,buffer.sampleRate,true);v.setUint32(28,buffer.sampleRate*ch*bps,true);v.setUint16(32,ch*bps,true);v.setUint16(34,bits,true);w(36,'data');v.setUint32(40,size,true);const data=Array.from({length:ch},(_,c)=>buffer.getChannelData(c));let o=44;for(let i=0;i<frames;i++)for(let c=0;c<ch;c++){const x=Math.max(-1,Math.min(1,data[c][i]));if(bits===8)v.setUint8(o++,Math.round((x+1)*127.5));else{v.setInt16(o,x<0?Math.round(x*32768):Math.round(x*32767),true);o+=2;}}return new Blob([out],{type:'audio/wav'});}
export async function processAudio(input,{speed=2,fidelity='cd',channels='stereo',autoTrim=true,context}={},hooks={}){const p=getPreset(fidelity),ctx=context||createAudioContext();hooks.progress?.(.05,'Decoding');let b=await decodeAudio(input,ctx);if(autoTrim){hooks.progress?.(.2,'Auto-trim');b=trimSilence(b);}hooks.progress?.(.35,'Channels');b=await convertChannels(b,channels==='mono'?1:2);hooks.progress?.(.55,'Speed ×2');b=await speedAndResample(b,speed,p.sampleRate);hooks.progress?.(.82,'Quantization');b=quantizeBuffer(b,p.bitDepth);hooks.progress?.(.92,'WAV encoding');const blob=encodeWav(b,p.bitDepth);hooks.progress?.(1,'Done');return{buffer:b,blob,sampleRate:p.sampleRate,bitDepth:p.bitDepth,channels:channels==='mono'?1:2};}
